### PR TITLE
Feat/responsive

### PR DESCRIPTION
**Pull request by jennieramida**
## Describe your changes
-  Support responsive on Tx and Account details

### CODE REVIEW

**Comment by tansawit** [comment]
JSON box not showing

CleanShot 2566-05-23 at 13 55 10@2x
CleanShot 2566-05-23 at 13 55 05@2x

**Comment by tansawit** [comment]
Search icon overlap with placeholder text

CleanShot 2566-05-23 at 13 55 43@2x

**Comment by tansawit** [comment]
is the IBC badge being on the second line intentional?

e.g. https://osmosis-celatone-frontend-staging-git-feat-responsive-alleslabs.vercel.app/mainnet/accounts/osmo1u2avtk5eh3h8g75fvt7vsh8jykjx9lpn5cylf8

CleanShot 2566-05-23 at 13 56 29@2x

**Comment by jennieramida** [comment]
- JSON box issue happened on both safari and chrome in iOS, need further inspection from @evilpeach 
- Search bar need to revise after merge this branch with `develop`
- IBC Tag misaligned fixed 😸

**Pull request closed without merging**
